// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPS
{
        public const string achievement_maybe_you_are_professional = "CgkIuYTB-6YdEAIQCg"; // <GPGSID>
        public const string achievement_youre_gonna_be_professional = "CgkIuYTB-6YdEAIQBA"; // <GPGSID>
        public const string achievement_more_coins = "CgkIuYTB-6YdEAIQCA"; // <GPGSID>
        public const string achievement_coins_loves_you = "CgkIuYTB-6YdEAIQCQ"; // <GPGSID>
        public const string achievement_beginner = "CgkIuYTB-6YdEAIQAg"; // <GPGSID>
        public const string achievement_nothing_hinders = "CgkIuYTB-6YdEAIQBw"; // <GPGSID>
        public const string achievement_first_jumps = "CgkIuYTB-6YdEAIQAw"; // <GPGSID>
        public const string achievement_can_you_give_me_some_money = "CgkIuYTB-6YdEAIQEA"; // <GPGSID>
        public const string achievement_you_found_it = "CgkIuYTB-6YdEAIQDQ"; // <GPGSID>
        public const string achievement_protection_is_important = "CgkIuYTB-6YdEAIQBg"; // <GPGSID>
        public const string achievement_on_the_road_to_wealth = "CgkIuYTB-6YdEAIQDg"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIuYTB-6YdEAIQAA"; // <GPGSID>
        public const string achievement_the_road_to_wealth = "CgkIuYTB-6YdEAIQBQ"; // <GPGSID>
        public const string achievement_rich_guy = "CgkIuYTB-6YdEAIQDw"; // <GPGSID>
        public const string achievement_you_are_definitely_a_professional = "CgkIuYTB-6YdEAIQCw"; // <GPGSID>
        public const string achievement_come_on_its_impossible_how_did_you_do_it = "CgkIuYTB-6YdEAIQDA"; // <GPGSID>

}

